# Generated by Django 2.0 on 2019-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20190610_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='amount',
            new_name='amount_invested',
        ),
        migrations.AddField(
            model_name='event',
            name='amount_recieved',
            field=models.IntegerField(default=0),
        ),
    ]
