# Generated by Django 2.0 on 2019-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20190610_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selected_team',
            field=models.CharField(default='', max_length=250),
        ),
    ]
