# Generated by Django 2.0 on 2019-06-10 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0012_event_selected_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='the_event_lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
