# Generated by Django 2.2 on 2019-06-16 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_event_event_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
