# Generated by Django 2.2 on 2019-06-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_article_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
